### PR TITLE
adding in new chat header and updated landing page

### PR DESCRIPTION
**Pull request by edwjchen**
## Checklist

- [N/A ] Did you write tests for your code?
- [N/A  ] Did all the tests pass locally?

## Trello Ticket

https://trello.com/c/JBkx3bnX/78-add-banner-on-top-move-log-out-button-into-banner-separate-from-chat-room-name

## Short Description

Separated logout button into a new chat header

## Reviewer Notes

image

### CODE REVIEW

**Comment by czhou29** [comment]
I think it would be better if we add a min-height property for the chat-header class to make sure that our application will still be rendered correctly even we reduce the size of the window. 
image
image

**Comment by czhou29** [comment]
And I also wondered whether we could change the style of the landing page's sign button to like this
<button class="btn btn-primary btn-lg" style="padding: 1.5vh 8vw;font-size: 1.5rem;">Sign In</button>
Jason imported the bootstrap frontend component framework at the very beginning, so in fact, it provided lots of in-built class styles and can render perfectly on different sizes of windows even on the mobile phone. Here are some links about bootstrap. Since we do not have enough time now, I guess it is good enough for our landing page now. 
image
image

https://getbootstrap.com/docs/4.0/utilities/display/
https://getbootstrap.com/docs/4.0/components/buttons/
https://getbootstrap.com/docs/4.0/utilities/spacing/

**Comment by czhou29** [comment]
If you want to use the Bootstrap component, remember to replace `class->className font-size->fontSize`, etc.

**Comment by czhou29** [comment]
Oh, my bad, I just noticed we only imported bootstrap CSS source code but not js source code, so only things related to style and resize will work. Collapse may not work now. So for navbar toggle, just ignore my suggestion and just use the plain navbar without any animation like the very first simple example.
image

**Comment by edwjchen** [comment]
Latest view:
image

**Review by albinencio — COMMENTED** [review]
When I look at the preview, the navbar doesn't show until I scroll up. Is that intentional? I think it'd be better for the navbar to always show, and to reduce the other two views' height (People + Chat) to still fit into the window altogether.

**Review by czhou29 — APPROVED** [review]
LGTM!

**Review by Joyfal — CHANGES_REQUESTED** [review]
Looks great, one NIT.

**Review by Joyfal — APPROVED** [review]

**Pull request merged**
